- src/TensorFlowNET.Core/Operations/OpDefLibrary.cs
Removing the line `var value = attrs[key];` removes the requirement for optional attributes to have a value.
Adding the check if the attr_def has a default value adds the check to ensure required attributes need a value.
Note that the behavior of Tensorflow in Python collects a list of missing attributes where as the implementation here throws a TypeError on the first missing required parameter (including inputs).
This isn't so much of a problem when using a Type Safe wrapper as it becomes difficult to pass in non-conforming attributes.
> Removing the requirment for optional attributes to have a value

- src/SciSharp.TensorFlow.Redist/SciSharp.TensorFlow.Redist.nupkgproj
Earlier, I had temporarily disabled the UpdateSHA feature. 
This checkin fixes and re-enables it back.
With this checkin, whenever we switch to a new version of tensorflow, it is possible to call "dotnet pack /p:UpdateSHA=true" and update the local .sha files (after updating the version number in the .nupkgproj and .nuspec file)
> Fixed behavior of UpdateSHA

- src/TensorFlowNET.Core/Tensors/Tensor.Operators.cs
- test/TensorFlowNET.UnitTest/OperationsTest.cs
Also unit testing all the operator cases.
> Add missing `operator -`s

- test/TensorFlowNET.UnitTest/gradients_test/GradientsTest.cs
Here are the functions tested
- Concat
- LGamma
- Tanh
- Slice  /!\  Slice seems not to work causing an error `System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.`
> Testing some gradients functions:

- src/TensorFlowNET.Core/APIs/tf.math.cs
- src/TensorFlowNET.Core/Gradients/math_grad.cs
- src/TensorFlowNET.Core/Operations/gen_math_ops.cs
- src/TensorFlowNET.Core/Operations/math_ops.cs
- src/TensorFlowNET.Core/tf.cs
- Adding new ctor for `Session`
Meant to be a shortcut to directly set some basic configuration.
E.g.
```
var sessionOptions = new SessionOptions();
sessionOptions.SetConfig(new ConfigProto
{
LogDevicePlacement = true,
InterOpParallelismThreads = 4,
GpuOptions = new GPUOptions
{
AllowGrowth = true,
PerProcessGpuMemoryFraction = 0.12
}
});
var session = tf.Session(sessionOptions);
```
- Adding `AbsGrad`
To be aligned with Tensorflow, introducing also `Sign` operation
and its gradient.
> Adding new ctor for `Session` and adding `AbsGrad`

- src/TensorFlowNET.Core/Tensors/Tensor.cs
A simple typo that led to a memory leak.
> fix memory leak due to wrong handle sent to api

- src/TensorFlowNET.Core/Gradients/array_grad.cs
- test/TensorFlowNET.UnitTest/gradients_test/GradientsTest.cs
The stop_gradient function is used to optimize part of the network without altering any previously trained part. It lacked its gradient.
> StopGradient: Adding basic gradient for stop_gradient function.

- src/TensorFlowNET.Core/Sessions/BaseSession.cs
- src/TensorFlowNET.Core/Tensors/TensorConverter.cs
- src/TensorFlowNET.Core/Tensors/dtypes.cs
- test/TensorFlowNET.UnitTest/SessionTest.cs
- test/TensorFlowNET.UnitTest/Utilities/FluentExtension.cs
In python, Tensorflow automatically casts input dtype to the expected dtype. 
Because we use `c_api`, this autocasting should be done by our code.
`input` placeholder is expecting `tf.float64`, given `np.array` is `tf.int32`. This code runs without a problem.
```python
with tf.Session().as_default() as sess:
input = tf.placeholder(tf.float64, shape=[6])
op = tf.reshape(input, [2, 3])
sess.run(tf.global_variables_initializer())
ret = sess.run(op, feed_dict={input: np.array([1, 2, 3, 4, 5, 6])})
print(ret)
```
> Added transparent dtype conversion to feed_dict

- src/TensorFlowNET.Core/APIs/tf.layers.cs
- src/TensorFlowNET.Core/Binding.Util.cs
- src/TensorFlowNET.Core/Binding.cs
- src/TensorFlowNET.Core/Tensors/TensorShape.cs
- src/TensorFlowNET.Core/tensorflow.cs
- test/TensorFlowNET.UnitTest/TensorShapeTest.cs
- test/TensorFlowNET.UnitTest/layers_test/flatten.cs
I've decided to make Binding.None to be null - only seems logical to follow python's logic in this case.
Example for use case:
``` C#
var sess = tf.Session().as_default();
var input = tf.placeholder(tf.float64, shape: new TensorShape(None, 3, 3));
//or: var input = tf.placeholder(tf.float64, shape: new []{None, 3, 3});
var op = input[3];
sess.run(tf.global_variables_initializer());
var input_data = np.arange(5 * 3 * 3).reshape((5, 3, 3));
var ret = sess.run(op, (input, input_data));
```
This fixed #377
> Added support for unknown dimension #377

- src/TensorFlowNET.Core/Binding.Util.cs
Exceptions should be left for the user to handle. Not printed to console and swallowed.
Issue #404 is a classic example to why. I got a null reference exception because `default(T)` was returned instead of the actual exception that described (at call of `status.Check(true)`) what I did wrong. My application had no console to show me the exception in.
> Removed exception swallowing from tf_with clauses

- src/TensorFlowNET.Core/Train/GradientDescentOptimizer.cs
Fixed a bug that over-writes the learning rate when sent as a Tensor in GradientDescentOptimizer.cs.
> Fixed a bug that over writes the learning rate when sent as a Tensor.

- src/TensorFlowNET.Core/Sessions/BaseSession.cs
In TF ByteString is more of a byte buffer than valid utf8. Reading it as a String adds escape characters to non-valid utf8. Then converting it to utf16 causes separate issues. Going from ByteString to byte[] fixes both of these.
> Using ByteString instead of String

- src/TensorFlowNET.Core/Sessions/BaseSession.cs
- test/TensorFlowNET.UnitTest/SessionTest.cs
fix NullReferenceException on session run with ITensorOrOperation signature.
Unfortunately I'm not able to run unit tests on my machine.
(I'm missing the native lib on mac and I don't have time to build it from source).
I hope that somebody on core team could help to validate this fix.
> fix NullReferenceException on session run

- src/TensorFlowNET.Core/Graphs/Graph.cs
- src/TensorFlowNET.Core/Tensors/tensor_util.cs
This PR (hopefully; I haven't tested the function other than it not throwing errors at build) implements: 
- `tensor_util.constant_value_as_shape`
- `graph._captures`
- `graph.external_captures`
- `graph.internal_captures`
It's my first PR here, and first time working with C# for more than toy purposes, so don't kill me if something here doesn't work like it should. 👍
> port constant_value_as_shape & some of its deps

- test/TensorFlowNET.UnitTest/ManagedAPI/GradientTest.cs
当对于张量乘法算式进行求导时，
无论是变量是单个数，还是常量是单个数，而另一个又是一个数组时，
如果组成乘法的算式将常量放乘法左边，变量放乘法右边，
对这个算式进行求导时，会发生求导返回值为 null 的情况。
> add GradientOperatorMulTest 。

- README.md
Per recent discussion with @Oceania2018, I've become a architect on SciSharp and will be working to improve the F# experience of using the major SciSharp projects. Part of this is to mention C# and F# equivalently in initial getting started material. This will help attract F# contributors.
This needs to be backed by F# samples and some documentation.  These will come in later pull requests.
> F# in README

- README.md
- Added example of eager mode linear regression to the readme
- Added the example data to the C# example
- Moved the links to documentation to the top of 'How to Use', because that made the most sense to me once we have examples in C# and F#.
> Add F# example to readme

- README.md
This is the proper way to mimic the C# `using static` code for opening Tensorflow.Binding and Tensorflow.KerasApi.
> use `open type` for F# readme example

- test/TensorFlowNET.UnitTest/Basics/RandomTest.cs
Currently the tests are set ignored because here's bug
Related to [Issue #746](https://github.com/SciSharp/TensorFlow.NET/issues/746)
> Add random seed test to help reproduce training

- src/TensorFlowNET.Keras/Preprocessings/Preprocessing.cs
- src/TensorFlowNET.Keras/Preprocessings/Tokenizer.cs
- src/TensorFlowNET.Keras/Sequence.cs
- src/TensorFlowNET.Keras/TextApi.cs
- test/TensorFlowNET.Keras.UnitTest/PreprocessingTests.cs
This adds the Keras Text.Tokenizer API, and adjusts the pad_sequences function to take the output of the Tokenizer without conversion. I tried to stay as close to the Python API as possible, which meant creating a 'Tokenizer()' factory method in the TextApi class.
I added unit tests for the Tokenizer and pad_sequences APIs.
> Adding subset of text preprocessing Keras APIs and unit tests.

- src/TensorFlowNET.Core/APIs/tf.random.cs
- src/TensorFlowNET.Core/Operations/Initializers/RandomUniform.cs
- src/TensorFlowNET.Core/Operations/array_ops.cs
- src/TensorFlowNET.Core/Operations/gen_array_ops.cs
- src/TensorFlowNET.Core/Operations/gen_random_ops.cs
- src/TensorFlowNET.Core/Operations/random_ops.cs
- src/TensorFlowNET.Keras/Layers/Core/Embedding.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/LayersTest.cs
- test/TensorFlowNET.UnitTest/ManagedAPI/ArrayOpsTest.cs
I added unit tests for slice and gather, and fixed the eager-mode implementation of gather.
I also added the ability to generate integer tensors with tf.random_uniform(), which is available in Python.
> Array operations

- src/TensorFlowNET.Core/Operations/gen_math_ops.cs
Hi :)
This is related to Issue #755. 
Multiple functions in gen_math_ops.cs result in "Attempting to capture an EagerTensor without building a function". For example, calling `tf.cos` works, but `tf.acos` results in an exception.
The issue seems to be anything that uses `tf.OpDefLib._apply_op_helper` instead of `tf.Context.ExecuteOp`
This merge fixes the issue for many methods in gen_math_ops. I would suggest having a look at what is left, because presumably these are still buggy.
> Fixed many simple functions in gen_math_ops.cs for "Attempting to capture an EagerTensor without building a function"

- src/TensorFlowNET.Core/Gradients/math_grad.cs
Currently, back-propagation is not implemented if you use acos, atan, or asin.
I've implemented these simple gradient functions
function references: 
https://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Derivatives_of_inverse_trigonometric_functions
or
http://www.math.com/tables/derivatives/tableof.htm
> Added gradients for acos, asin, atan

- src/TensorFlowNET.Core/Tensors/Tensor.Creation.cs
This fixes the following bug:
- Create a numpy array that is 25,763 x 25,763
- Implicitly convert to a `Tensor` object
- An `AccessViolationException` is thrown
This is because the lengths of the arrays are not calculated properly - casting to a ulong occurs /after/ the multiplication. As such, it tries to read past the end of the array
> Fix casting issue causing AccessViolationException

- src/TensorFlowNET.Core/Operations/gen_array_ops.cs
- src/TensorFlowNET.Core/Operations/gen_math_ops.cs
Hiya,
This follows up my previous merge request (#783) with more methods that crash with Attempting to capture an EagerTensor without building a function
fixed are `log`, `arg_min`, `_min`, `_max`
Cheers
> Gen array ops bug fixes

- docs/source/LinearRegression.md
- docs/source/LogisticRegression.md
- docs/source/NearestNeighbor.md
Some links to the examples were not working. This PR links to the right directory.
> docs: fix links to examples

- src/TensorFlowNET.Keras/Engine/Layer.Apply.cs
If trying to run predict method from new Thread or Task callContext does not contains Value. This small fix check that check if callContext is null or callContext.Value is null create a new  ThreadLocal with CallContext.
> Check if callContext is null or callContext.Value is null create a new  ThreadLocal with CallContext. 

- src/TensorFlowNET.Core/Graphs/Graph.cs
- src/TensorFlowNET.Keras/BackendImpl.cs
testing a conv2d autoencoder from
https://keras.io/guides/functional_api/#:~:text=keras.,graph%20(DAG)%20of%20layers
revealed that layer names ending in / could be duplicated in the graph, preventing the model from being compiled. This fix resolved the duplicate layer name issue.
> Fix duplicate graph node name

- src/TensorFlowNET.Core/Tensorflow.Binding.csproj
- test/TensorFlowNET.Keras.UnitTest/PreprocessingTests.cs
The dependency on `Microsoft.Extensions.DependencyInjection` is unused and can be safely removed.
This PR fixes #920.
> Remove unused dependency

- src/TensorFlowNET.Core/Sessions/BaseSession.cs
In multithreading .NET 4.8 applications, sometimes in Session finalizer the method c_api.TF_DeleteSession find f.Status static instance already disposed for some reason. No problem for .NET 6 application or with a single thread. (https://github.com/SciSharp/TensorFlow.NET/issues/912)
> Removed use of tf.Status static instance

- src/TensorFlowNET.Core/Gradients/Tape.ComputeGradient.cs
- src/TensorFlowNET.Core/Gradients/math_grad.cs
- src/TensorFlowNET.Core/Keras/Layers/ILayersApi.cs
Fix #974 
It seems that this problem is caused because `unneeded_gradients` is unused.
Besides, `Rsqrt` gradient is not registered and `Conv2DTranspose` is not declared in `ILayersApi`.
This PR resolved the problems above. @Oceania2018 Please have a review, especially the modification of `Tape.ComputeGradient.cs`.
> Fix ConvTraspose2D gradient and register rsqrt gradient.

- src/TensorFlowNET.Keras/Losses/SparseCategoricalCrossentropy.cs
Fix: #985 
It seems that this issue is not caused by `softmax` but `sparse_categorical_crossentropy`. It is actually because the `from_logits` parameter is ignored.
> Fix the keras.sparse_categorical_crossentropy. (#985)

- src/TensorFlowNET.Core/Keras/Layers/ILayersApi.cs
- src/TensorFlowNET.Keras/KerasInterface.cs
- src/TensorFlowNET.Keras/Layers/LayersApi.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/AttentionTest.cs
Align the definition and implementation of keras.Input with tensorflow python.
> Align keras.Input with tensorflow python.

- README.md
- docs/Example-fsharp.md
- docs/README-CN.md
Optimize the the readme and add Chinese version readme.
> Optimize the readme files

- src/TensorFlowNET.Core/Keras/Layers/ILayersApi.Activation.cs
- src/TensorFlowNET.Keras/Layers/LayersApi.Activation.cs
- test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelSave.cs
In python we often use `keras.softmax` without parameters because it set default parameter `axis = -1`.
This PR adds an overload of `keras.softmax` to align the behavior with tensorflow python.
> Add default value of parameter of keras softmax.

- src/TensorFlowNET.Core/Data/DatasetV2.cs
- src/TensorFlowNET.Core/Data/IDatasetV2.cs
- src/TensorFlowNET.Core/Data/OwnedIterator.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/DataAdapterArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/DataHandlerArgs.cs
- src/TensorFlowNET.Core/Keras/Engine/IModel.cs
- src/TensorFlowNET.Core/NumPy/NDArray.Implicit.cs
- src/TensorFlowNET.Core/NumPy/Persistence/NpzDictionaryArray.cs
- src/TensorFlowNET.Core/Numpy/NDArray.cs
- src/TensorFlowNET.Core/Operations/dataset_ops.cs
- src/TensorFlowNET.Core/Tensors/Tensors.cs
- src/TensorFlowNET.Keras/Engine/DataAdapters/DataAdapter.cs
- src/TensorFlowNET.Keras/Engine/DataAdapters/DataHandler.cs
- src/TensorFlowNET.Keras/Engine/DataAdapters/IDataAdapter.cs
- src/TensorFlowNET.Keras/Engine/DataAdapters/TensorLikeDataAdapter.cs
- src/TensorFlowNET.Keras/Engine/Model.Fit.cs
- src/TensorFlowNET.Keras/Engine/Model.Train.cs
- test/TensorFlowNET.Keras.UnitTest/Helpers/RandomDataset.cs
- test/TensorFlowNET.Keras.UnitTest/MultiInputModelTest.cs
- test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelLoad.cs
- test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelSave.cs
- test/TensorFlowNET.UnitTest/Dataset/DatasetTest.cs
Partially fix #939 
It mainly did two things:
1. Support the multiple inputs of keras `model.fit`.
2. Update the `anonymous_iterator_v2` to `anonymous_iterator_v3`.
It made the following break changes:
1. Removed the implicit conversionfrom `Array` to `NDArray`. Instead, it added a series implicit conversion such as `int[]`, `float[,]`, `double[,,]` and so on.
2. It makes `IDatasetV2` implements `IEnumerable<(Tensors, Tensors)>` instead of `IEnumerable<(Tensor, Tensor)>`. (This may lead to some error of examples.)
> Support the multiple inputs of keras model.fit.

- src/TensorFlowNET.Console/Program.cs
- src/TensorFlowNET.Core/Keras/IKerasApi.cs
- src/TensorFlowNET.Core/Keras/IOptimizerApi.cs
- src/TensorFlowNET.Core/Keras/Models/IModelsApi.cs
- src/TensorFlowNET.Core/tensorflow.cs
- src/TensorFlowNET.Keras/KerasApi.cs
- src/TensorFlowNET.Keras/KerasInterface.cs
- src/TensorFlowNET.Keras/Models/ModelsApi.cs
- test/TensorFlowNET.Keras.UnitTest/EagerModeTestBase.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/LayersTest.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/ModelSaveTest.cs
Since the package `Tensorflow.Keras` is separated with `Tensorflow.NET`, users need to add `tf.UseKeras<KerasInterface>();` to enable the `tf.keras`. This PR use lazy loaded singleton mode to automatically enable `tf.keras`. Besides, it add some extra supports, which are `IOptimizerApi` and `IModelsApi`.
However, some important API such as `Activation` is still unable to be aligned because of the separation of the two packages.
> Automatically add KerasInterface to tf

- src/TensorFlowNET.Core/Data/OwnedIterator.cs
- src/TensorFlowNET.Core/Keras/Engine/IModel.cs
- src/TensorFlowNET.Keras/Engine/Model.Predict.cs
- test/TensorFlowNET.Keras.UnitTest/MultiInputModelTest.cs
Support mutiple inputs of keras modek.predict. It works along with #996 and fix #939
> Support mutiple inputs of keras modek.predict.

- src/TensorFlowNET.Core/Keras/Activations/Activations.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Convolution/ConvolutionalArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Core/DenseArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Core/EinsumDenseArgs.cs
- src/TensorFlowNET.Core/Keras/Common/CustomizedActivationJsonConverter.cs
- src/TensorFlowNET.Core/Keras/IKerasApi.cs
- src/TensorFlowNET.Keras/Activations.cs
- src/TensorFlowNET.Keras/KerasInterface.cs
- src/TensorFlowNET.Keras/Layers/Convolution/Conv2DTranspose.cs
- src/TensorFlowNET.Keras/Layers/Convolution/Convolutional.cs
- src/TensorFlowNET.Keras/Layers/Core/Dense.cs
- src/TensorFlowNET.Keras/Layers/Core/EinsumDense.cs
- src/TensorFlowNET.Keras/Layers/LayersApi.cs
- test/TensorFlowNET.Keras.UnitTest/GradientTest.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/ActivationTest.cs
- test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelSave.cs
fix: #991 
This issue is actually not because of wrong computation but the absence of activation when loading model. And this is because the previous design separates `Activation` and `ActivationName` in `LayerArgs`. Therefore when loading the model, the `ActivationName` is assigned but `Activation` not.
This PR made the following changes:
1. Use a class to wrap the activation function and provide a method `Apply` to make it similar to calling a layer.
2. Add customized json converter for `Activation` to make it work with model loading.
3. Benefited from 1, `tf.keras.activations` can be added to align with tensorflow python.
> Refine keras.Activation and add tf.keras.activations.

- src/TensorFlowNET.Core/Keras/Engine/ICallback.cs
- src/TensorFlowNET.Keras/Callbacks/CallbackList.cs
- src/TensorFlowNET.Keras/Callbacks/History.cs
- src/TensorFlowNET.Keras/Callbacks/ProgbarLogger.cs
- src/TensorFlowNET.Keras/Engine/Model.Evaluate.cs
> Fix model.evaluate don't have output

- src/TensorFlowNET.Core/Keras/Engine/ICallback.cs
- src/TensorFlowNET.Core/Keras/Engine/IModel.cs
- src/TensorFlowNET.Keras/Callbacks/CallbackList.cs
- src/TensorFlowNET.Keras/Callbacks/Earlystopping.cs
- src/TensorFlowNET.Keras/Callbacks/History.cs
- src/TensorFlowNET.Keras/Callbacks/ProgbarLogger.cs
- src/TensorFlowNET.Keras/Engine/Model.Fit.cs
- src/TensorFlowNET.Keras/Engine/Model.cs
- test/TensorFlowNET.Keras.UnitTest/Callbacks/EarlystoppingTest.cs
> Add EarlyStopping callback

- src/TensorFlowNET.Core/Keras/Engine/IModel.cs
- src/TensorFlowNET.Keras/Callbacks/Earlystopping.cs
- src/TensorFlowNET.Keras/Engine/Model.cs
Adding a Stop_training property to set stop_training may be more elegant instead of define a set_stoptraining_true function.
> Add a Stop_training property 

- src/TensorFlowNET.Core/Keras/Engine/ICallback.cs
- src/TensorFlowNET.Core/Keras/Engine/IModel.cs
- src/TensorFlowNET.Keras/Callbacks/CallbackList.cs
- src/TensorFlowNET.Keras/Callbacks/Earlystopping.cs
- src/TensorFlowNET.Keras/Callbacks/History.cs
- src/TensorFlowNET.Keras/Callbacks/ProgbarLogger.cs
- src/TensorFlowNET.Keras/Engine/Model.Evaluate.cs
- src/TensorFlowNET.Keras/Engine/Model.Fit.cs
Fix validation_split has no output and add validation_data parameter to model.fit and the definition of logs has been modified to align with the log form of train (DIctionary<string, float>)
> Fix validation_split has no output and add validation_data parameter to model.fit

- src/TensorFlowNET.Core/APIs/tf.signal.cs
- src/TensorFlowNET.Core/Operations/gen_ops.cs
- test/TensorFlowNET.Graph.UnitTest/SignalTest.cs
Fourier transforms and unit tests for them.
> Added: fft, ifft, fft2d, ifft2d, fft3d, ifft3d

- src/TensorFlowNET.Keras/Losses/SparseCategoricalCrossentropy.cs
I found that the reason why the model does not converge lies in this SparseCategoricalCrossentropy function, when I change it to CategoricalCrossentropy and do ont-hot on y_train it works well. So the problem is this loss function. I found the from_logits used by the Apply function is not the from_logits that comes in the constructor. So it will always be false even if we specify it as true when we use SparseCategoricalCrossentropy.
> Fix the bug of non-convergence when use SparseCategoricalCrossentropy

- src/TensorFlowNET.Core/Checkpoint/SaveUtilV1.cs
- src/TensorFlowNET.Core/Checkpoint/checkpoint.cs
- src/TensorFlowNET.Core/Checkpoint/functional_saver.cs
- src/TensorFlowNET.Core/Contexts/Context.Device.cs
- src/TensorFlowNET.Core/Contexts/Context.cs
- src/TensorFlowNET.Core/Contexts/EagerDeviceContext.cs
- src/TensorFlowNET.Core/Device/DeviceSpec.cs
- src/TensorFlowNET.Core/Device/DeviceUtils.cs
- src/TensorFlowNET.Core/Graphs/Graph.cs
- src/TensorFlowNET.Core/Graphs/GraphDeviceContext.cs
- src/TensorFlowNET.Core/Training/Saving/ResourceVariableSaveable.cs
- src/TensorFlowNET.Core/Training/Saving/SavedModel/loader.cs
- src/TensorFlowNET.Core/Variables/BaseResourceVariable.cs
- src/TensorFlowNET.Core/Variables/UninitializedVariable.cs
- src/TensorFlowNET.Core/ops.cs
Fix the error when saving model with GPU. The `DeviceSpec` was also added.
> Fix the error when saving model with GPU.

- TensorFlow.NET.sln
- src/TensorFlowNET.Core/Tensors/Tensors.cs
- src/TensorFlowNET.Core/Tensors/dtypes.cs
- src/TensorFlowNET.Keras/Engine/Layer.AddWeights.cs
- src/TensorFlowNET.Keras/Saving/KerasMetaData.cs
- src/TensorFlowNET.Keras/Saving/KerasObjectLoader.cs
- src/TensorFlowNET.Keras/Saving/SavedModel/RevivedInputLayer.cs
- src/TensorFlowNET.Keras/Saving/SavedModel/RevivedLayer.cs
- src/TensorFlowNET.Keras/Saving/SavedModel/RevivedNetwork.cs
- src/TensorflowNET.Hub/GcsCompressedFileResolver.cs
- src/TensorflowNET.Hub/HttpCompressedFileResolver.cs
- src/TensorflowNET.Hub/HttpUncompressedFileResolver.cs
- src/TensorflowNET.Hub/KerasLayer.cs
- src/TensorflowNET.Hub/Tensorflow.Hub.csproj
- src/TensorflowNET.Hub/file_utils.cs
- src/TensorflowNET.Hub/hub.cs
- src/TensorflowNET.Hub/module_v2.cs
- src/TensorflowNET.Hub/registry.cs
- src/TensorflowNET.Hub/resolver.cs
- src/TensorflowNET.Hub/tf_utils.cs
- test/TensorflowNET.Hub.Unittest/KerasLayerTest.cs
- test/TensorflowNET.Hub.Unittest/Tensorflow.Hub.Unittest.csproj
- test/TensorflowNET.Hub.Unittest/Usings.cs
This PR added the following features:
1. Add the tensorflow.net.hub (but hasn't made any package).
2. Implement the `KerasLayer`, which supports to load pretrained model in tensorflow.net.keras. The unittest shown how to load a small bert model and predict the result. However, note that the backward process has not been ensured now.
3. Support downloading the model from website. (Note that only downloading from tensorflow hub website is ensured now).
> Add Tensorflow.NET.Hub

- src/TensorFlowNET.Core/NumPy/Persistence/NpyFormat.cs
- src/TensorFlowNET.Core/Numpy/NDArray.Creation.cs
- src/TensorFlowNET.Core/Operations/array_ops.cs
- src/TensorFlowNET.Core/Tensors/c_api.tensor.cs
- src/TensorFlowNET.Core/Tensors/tensor_util.cs
This PR made the following changes:
1. Fix the error when saving NDArray with dtype=byte.
2. Add a protected constructor for NDArray, which allows to reuse the existing memory to create a NDArray.
> Add the constructor of NDArray which reuses memory

- src/TensorFlowNET.Core/Device/DeviceSpec.cs
- test/TensorFlowNET.UnitTest/Basics/ThreadSafeTest.cs
> fix: error when using graph in multi-threads.

- src/TensorFlowNET.Keras/Activations.cs
Solve 1st problem of #1012
The bug is caused by the unchecked variable in GetActivationFromName().
In original TensorFlow, the corresponding method just [returns the 'linear' function](https://github.com/tensorflow/tensorflow/blob/f5157cf2fefe18ffd82a50df4b1d18fd39631123/tensorflow/python/keras/activations.py#LL594C5-L594C12) when encountering this null situation. 
I solved the problem in their way.
Thanks!
> fix: error when set the activation of keras.layers.Conv2DTranspose to null.

- src/TensorFlowNET.Keras/Layers/Convolution/Conv2DTranspose.cs
Solve 2nd problem of #1012
Before solving the issue, I found another bug in Conv2DTranspose.build(). The len() cannot be used for input_shape after the commit 747e658, which change the type of input_shape from Shape to KerasShapesWrapper. I solved it by using len(single_shape) instead of len(input_shape), where single_shape = input_shape.ToSingleShape().
Back to the issue, the NotImplementedException raised because the lack of implement to handle 'use_bias' in 'Call' process of Conv2DTranspose. I add the code referring [original TensorFlow](https://github.com/tensorflow/tensorflow/blob/ab388e4485dab64a3a0c421a564a358b4d3381f2/tensorflow/python/keras/layers/convolutional.py#LL1335C18-L1335C18).
Thanks!
> fix: can't implement len for KerasShapesWrapper & Add bias implement to Conv2DTranspose.Call()

- src/TensorFlowNET.Core/Training/Saving/SavedModel/save.cs
- src/TensorFlowNET.Keras/Engine/Layer.Apply.cs
- src/TensorFlowNET.Keras/Engine/Layer.cs
- src/TensorFlowNET.Keras/Engine/Sequential.cs
- test/TensorFlowNET.Keras.UnitTest/Model/ModelBuildTest.cs
Fix: #1084 
It's only a temporary fix and need re-consideration, please don't merge it now.
> fix: temporarily fix the sequential nest error.

- src/TensorFlowNET.Core/NumPy/Numpy.Math.cs
- test/TensorFlowNET.UnitTest/Numpy/Math.Test.cs
Solve the problem that NDArray.max() does not support max from multiple dimensions and add a TestMethod. #635 
And the NDArray.sum() method has already supported max from multiple dimensions.
Thanks!
> fix: A new feature for NDArray.max 

- src/TensorFlowNET.Core/APIs/c_api.cs
- src/TensorFlowNET.Core/APIs/c_api.customize.cs
- src/TensorFlowNET.Core/Eager/GraphOnlyOps.cs
- src/TensorFlowNET.Core/Graphs/FuncGraph.cs
- src/TensorFlowNET.Core/Operations/list_ops.cs
- src/TensorFlowNET.Core/Operations/while_v2.cs
- src/TensorFlowNET.Core/ops.cs
- tools/Tensorflow.UnitTest.RedistHolder/Tensorflow.UnitTest.RedistHolder.csproj
The fix comes along with new backends:
- Tensorflow.Redist - v2.11.4
- Tensorflow.Redist-Windows-Gpu - v2.10.3
- Tensorflow.Redist-Linux-Gpu - v2.11.1
> fix: error pf training RNN on Linux

- src/TensorFlowNET.Core/APIs/tf.nn.cs
- src/TensorFlowNET.Keras/Layers/Normalization/LayerNormalization.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/LayersTest.cs
The ` LayerNormalization` didn't work as expected, it throws an `System.NullReferenceException` during runtime.
> Improve the API of  LayerNormalization

- src/TensorFlowNET.Core/NumPy/NDArray.Implicit.cs
- src/TensorFlowNET.Core/Operations/array_ops.cs
- test/TensorFlowNET.UnitTest/Dataset/DatasetTest.cs
Add some implicit operators and dtype processing cases so that the `imdb` loader can work as expected.
> fix: type converting errors when loading imdb dataset

- src/TensorFlowNET.Keras/Losses/BinaryCrossentropy.cs
- src/TensorFlowNET.Keras/Losses/CategoricalCrossentropy.cs
- src/TensorFlowNET.Keras/Losses/CosineSimilarity.cs
- src/TensorFlowNET.Keras/Losses/Huber.cs
- src/TensorFlowNET.Keras/Losses/LogCosh.cs
- src/TensorFlowNET.Keras/Losses/Loss.cs
- src/TensorFlowNET.Keras/Losses/LossFunctionWrapper.cs
- src/TensorFlowNET.Keras/Losses/MeanAbsoluteError.cs
- src/TensorFlowNET.Keras/Losses/MeanAbsolutePercentageError.cs
- src/TensorFlowNET.Keras/Losses/MeanSquaredError.cs
- src/TensorFlowNET.Keras/Losses/MeanSquaredLogarithmicError.cs
- src/TensorFlowNET.Keras/Losses/SigmoidFocalCrossEntropy.cs
- src/TensorFlowNET.Keras/Losses/SparseCategoricalCrossentropy.cs
abstract Loos.Apply instead of virtualy throw exception
abstract class LossFunctionWrapper
Smooth implementation of sub class
Move ILossFunc to base abstract class Loss
> refactor: Standardize TensorFlowNET.Keras/Losses/*

- src/TensorFlowNET.Core/Keras/Engine/ICallback.cs
- src/TensorFlowNET.Core/Keras/Engine/IModel.cs
- src/TensorFlowNET.Keras/Callbacks/CallbackList.cs
- src/TensorFlowNET.Keras/Callbacks/Earlystopping.cs
- src/TensorFlowNET.Keras/Callbacks/History.cs
- src/TensorFlowNET.Keras/Callbacks/ProgbarLogger.cs
- src/TensorFlowNET.Keras/Engine/Model.Evaluate.cs
- src/TensorFlowNET.Keras/Engine/Model.Fit.cs
There were some problems in the previous modification of model.evaluate, which caused model.evaluate to be called when the validation_split of model.fit was not empty, resulting in an abnormal output of the progress bar.
> fix: fix the bug of repeated progress bar in Model.fit()

- src/TensorFlowNET.Keras/Saving/KerasObjectLoader.cs
I added `ToArray()` so that there is no "The collection has changed" error after `_delete_tracking`.
> fix: A bug fix in KerasObjectLoader.cs

- src/TensorFlowNET.Core/Framework/IndexedSlices.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/LayersTest.cs
Fixed issue #916. The bug is caused by an incorrect implicit operator that trys to convert a `IndexedSlices` to `Tensor` but only returns the values of `IndexedSlices`. As a result, the gradient of the embedding layer is not restored to the dense tensor and its shape is inconsistent with the shape of the parameters.
> fix: inconsistent shape error while training embedding layer

- src/TensorFlowNET.Core/APIs/tf.nn.cs
- src/TensorFlowNET.Core/Operations/array_ops.cs
`tf.nn.moments` : There may be a problem where the gradient is `null` during the training,  it seems that removing the 681st line of code from the `[TensorFlowNET.Core/Operations/array_ops.cs]` can solve this issue.
`tf.nn.batch_normalization`: Use `nn_impl.batch_normalization` to reuse code.
> fix: optimize some APIs

- src/TensorFlowNET.Keras/Saving/hdf5_format.cs
`model.save_weights` :  When the weight name is nested multiple times (e.g. when the model has two weight names:  `bert/layer/dense/kernal:0` and `bert/layer/dense_1/bias:0` the weight saved by  `bert/layer/dense/kernal:0` may overwritten by `bert/layer/dense_1/bias:0`), the API doesn't work as expected.
> fix: Fix the problem where the  model.save_weights() can't save multi-layer weight

- test/TensorFlowNET.Keras.UnitTest/Model/ModelLoadTest.cs
In order to avoid affecting the subsequent PR, ignore this test temporarily.
> fix: ignore the LSTMLoad test

- src/TensorFlowNET.Core/NumPy/NumPy.Sorting.Searching.Counting.cs
- src/TensorFlowNET.Core/NumPy/NumPy.Statistics.cs
- src/TensorFlowNET.Core/Operations/math_ops.cs
> fix: revise np.amin, np.amax and add np.argmin

- src/TensorFlowNET.Core/APIs/tf.image.cs
- src/TensorFlowNET.Core/Operations/gen_image_ops.cs
- test/TensorFlowNET.Graph.UnitTest/ImageTest.cs
Because the oprs related to tf.image in tf.net is missing a lot, so add some oprs and test.
> feat: add adjust_contrast, adjust_hue, combined_non_max_suppression, crop_and_resize image oprs

- src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/ExponentialArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/HardSigmoidArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/SELUArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/SoftplusArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/SoftsignArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/SwishArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/TanhArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Convolution/Conv2DTransposeArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Merging/AddArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Merging/ConcatenateArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Merging/SubtractArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Pooling/GlobalAveragePooling1DArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Pooling/GlobalAveragePooling2DArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Pooling/GlobalMaxPooling1DArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Pooling/GlobalMaxPooling2DArgs.cs
- src/TensorFlowNET.Core/Keras/ArgsDefinition/Pooling/MaxPooling1DArgs.cs
- src/TensorFlowNET.Keras/Layers/LayersApi.Activation.cs
- src/TensorFlowNET.Keras/Layers/LayersApi.Merging.cs
- src/TensorFlowNET.Keras/Layers/LayersApi.cs
Load_model use reflection to revive LayerArgs and then revive Layer.
https://github.com/SciSharp/TensorFlow.NET/blob/adeed05f64cf033a7d945d97ba4b59bc5ec4aa03/src/TensorFlowNET.Keras/Utils/generic_utils.cs#L64-L69
So each layer's args must be the pattern of {class_name}Args, otherwise it cannot be revived.
> fix: partially fix the bug of load_model

- src/TensorFlowNET.Keras/Engine/Model.Fit.cs
Did not test it, but debugging showed that this is the code that is missing. `stop_training` is only updated but never used.
This solves #1170
> fix: model does not stop on stop_training == true #1170

- test/TensorFlowNET.Graph.UnitTest/ControlFlowTest/WhileContextTestCase.cs
- test/TensorFlowNET.Graph.UnitTest/GradientTest/GradientTest.cs
- test/TensorFlowNET.Graph.UnitTest/PythonTest.cs
Implementation of cached_session for the possibility of further porting of tests. 
cached_session is a singleton which is constructed on the first call and disposed on the tests cleanup.
There's also testBoundaryContinue() test implemented to prove that cache_session() works.
> cached_session for graph tests

- src/TensorFlowNET.Core/Keras/ArgsDefinition/Merging/MergeArgs.cs
- src/TensorFlowNET.Core/NumPy/Numpy.Manipulation.cs
- src/TensorFlowNET.Keras/Engine/Functional.FromConfig.cs
- src/TensorFlowNET.Keras/Layers/Merging/Concatenate.cs
- src/TensorFlowNET.Keras/Utils/generic_utils.cs
- test/TensorFlowNET.Keras.UnitTest/Layers/Layers.Merging.Test.cs
- test/TensorFlowNET.Keras.UnitTest/Model/ModelLoadTest.cs
This is my first serious pullrequest so please be gentle :)
The `tf.keras.models.load_model()` is now able to load models with this layer type.
There was a lot missing but I have a Unet model running in the field that now fully works.
I had some weird troubles with python tensorflow (im using 2.11.1) that savemodel would put the inbound nodes for concatenate layers in an extra nested array. My call in python looks like:
```python
comb = layers.Concatenate(axis=3, name=name+"_concat1")([concat_layer,conv])
```
This would create the following output in the manifest (notice the extra `[` and `]`:
```json
{
"class_name": "Concatenate",
"config": {
"name": "EXP_1_concat1",
"trainable": true,
"dtype": "float32",
"axis": 3
},
"name": "EXP_1_concat1",
"inbound_nodes": [
[
[
"CNT_4_conv_2",
0,
0, …
```
> fix: Implemented support for loading models with Concatenate layers

- src/TensorFlowNET.Core/Operations/NnOps/rnn.cs
- src/TensorFlowNET.Core/Operations/array_ops.cs
- src/TensorFlowNET.Core/Operations/nn_ops.cs
- test/TensorFlowNET.Graph.UnitTest/Basics/TensorTest.cs
> fix: fix the bug of boolean_mask

- src/TensorFlowNET.Core/Util/Data.cs
- src/TensorFlowNET.Keras/Engine/DataAdapters/DataAdapter.cs
- src/TensorFlowNET.Keras/Engine/Model.Evaluate.cs
- src/TensorFlowNET.Keras/Engine/Model.Fit.cs
> fix: fix the validation_pack when multiple input

- src/TensorFlowNET.Keras/Layers/LayersApi.cs
Conv2dTranspose defaults to have use_bias = true but currently throws a not implemented exception when the parameter is true.
> Fix Conv2dTranspose bias

- src/TensorFlowNET.Core/Training/Saving/SavedModel/AugmentedGraphView.cs
Change code to avoid modifying the cache collection while maintaining the loops
> fix: Avoid modifying augmented graph view collection upon traversal

- src/TensorFlowNET.Keras/Engine/Model.Evaluate.cs
- src/TensorFlowNET.Keras/Engine/Model.Fit.cs
- test/TensorFlowNET.Keras.UnitTest/MultiInputModelTest.cs
A small addition to support multi-input datasets.
> fix: Support for training a multi-input model using a dataset.

- src/TensorFlowNET.Keras/Engine/Functional.cs
Replace `.ToArray() `with `.ToList()` to allow dynamic modification of `network_nodes` in **`MapGraphNetwork()`**
Replaced `.ToArray() `with `.ToList()` to resolve the issue where `.Add()` was called on a fixed-size array.
This preventing the "_Collection was of a fixed size_" error when called something like this `var model = keras.Model(new Tensors(new Tensor[] { encoder_inputs, decoder_inputs }), outputs: decoder_dense);`
> fix: Resolve fixed-size array issue
