SciSharp/TensorFlow.NET

src/TensorFlowNET.Core/Graphs/Graph.Operation.cs
src/TensorFlowNET.Core/Operations/Operation.cs
src/TensorFlowNET.Core/Operations/OperationDescription.cs
src/TensorFlowNET.Core/Operations/c_api.ops.cs
test/TensorFlowNET.UnitTest/CApiColocationTest.cs
test/TensorFlowNET.UnitTest/GraphTest.cs
test/TensorFlowNET.UnitTest/c_test_util.cs

add FinishOperation to OperationDescription

---

src/TensorFlowNET.Core/Attributes/c_api.ops.cs
src/TensorFlowNET.Core/Operations/c_api.ops.cs
test/TensorFlowNET.UnitTest/CApiGradientsTest.cs
test/TensorFlowNET.UnitTest/CApiTest.cs

c_api.TF_SetAttrTensor exception threw.
move attributes to new folder.

 CApiGradientsTest

---

docs/source/LinearRegression.md

Finished the translation of linear regression.

Linear Regression  translation

---

docs/source/LogisticRegression.md

Update the definition of Logistic Regression

Update Logistic Regression

---

src/TensorFlowNET.Core/Graphs/Graph.Control.cs
src/TensorFlowNET.Core/Operations/Operation.cs
src/TensorFlowNET.Core/Train/GradientDescentOptimizer.cs
src/TensorFlowNET.Core/ops.py.cs
src/TensorFlowNET.Visualization/TensorFlowNET.Visualization.csproj
test/TensorFlowNET.Examples/TensorFlowNET.Examples.csproj
test/TensorFlowNET.UnitTest/ControlDependenciesTest.cs
test/TensorFlowNET.UnitTest/TensorFlowNET.UnitTest.csproj

Sorry for the downgrade of .net core to 2.1, but it still compiles fine.

Ported a test case from ops_test.py and fixed a bug that was revealed by it

---

src/TensorFlowNET.Core/Graphs/Graph.Control.cs
src/TensorFlowNET.Core/Operations/ControlFlows/CondContext.cs
src/TensorFlowNET.Core/Operations/ControlFlows/ControlFlowContext.cs
src/TensorFlowNET.Core/Operations/control_flow_ops.py.cs
src/TensorFlowNET.Core/Python.cs
test/TensorFlowNET.UnitTest/CreateOpFromTfOperationTest.cs
test/TensorFlowNET.UnitTest/PythonTest.cs

Please review my changes before merging. I am not 100% sure about them, but without the changes we get NullRefExceptions.  
Check out CreateOpFromTfOperationTest.TestCond test case to see what is still not right with control flow.

Changes to Cond and Control Flow Context

---

src/TensorFlowNET.Core/Graphs/Graph.Operation.cs
src/TensorFlowNET.Core/Operations/ControlFlows/CondContext.cs
src/TensorFlowNET.Core/Operations/ControlFlows/ControlFlowContext.cs
src/TensorFlowNET.Core/Operations/ControlFlows/IControlFlowContext.cs
src/TensorFlowNET.Core/Operations/Operation.Control.cs
src/TensorFlowNET.Core/Operations/Operation.cs
src/TensorFlowNET.Core/Operations/control_flow_ops.py.cs
src/TensorFlowNET.Core/Operations/gen_control_flow_ops.py.cs
test/TensorFlowNET.UnitTest/ops_test/CreateOpFromTfOperationTest.cs

CondContext: implemented missing functionality

---

src/TensorFlowNET.Core/Python.cs

Hey guys, I havent added the tests for these functions... and do we really need test for these??? I mean they are for base python functions ported to C# and not Tensorflow specific functions....

added hasattr() and getattr()

---

README.md
docs/source/ImageRecognition.md
docs/source/LinearRegression.md
docs/source/LogisticRegression.md
docs/source/NearestNeighbor.md

Corrected links to models and folders in the documentation and readme.md alike.

Fixed the broken links to examples.

---

tensorflowlib/README.md

- Added link for GPU version
- Added note for cuda cudnn installation

Updating readme file regarding WIndows GPU Tensorflow

---

src/TensorFlowNET.Core/Train/AdamOptimizer.cs
test/TensorFlowNET.Examples/TextProcess/CnnTextClassification.cs
test/TensorFlowNET.UnitTest/ExamplesTests/ExamplesTest.cs

CnnTextClassification debugging

---

src/TensorFlowNET.Core/APIs/tf.linalg.cs
src/TensorFlowNET.Core/Gradients/math_grad.cs
src/TensorFlowNET.Core/Operations/gen_math_ops.cs
src/TensorFlowNET.Core/Operations/math_ops.cs
test/TensorFlowNET.Examples/BasicOperations.cs

Adding the `BatchMatMul` operation.
Expanding `BasicOperations` to test the new operation.

Add `BatchMatMul` operation

---

src/TensorFlowNET.Core/Tensors/Tensor.Operators.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Also unit testing all the operator cases.

Add missing `operator +`s

---

src/TensorFlowNET.Core/Gradients/math_grad.cs
test/TensorFlowNET.UnitTest/gradients_test/GradientsTest.cs

Unit testing the gradient too.

Adding `BatchMatMul` gradient

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/Operations/gen_math_ops.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Exposing also the `IsFinite` one.
Unit testing both operations.

Adding `IsNan` operation

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/Operations/gen_math_ops.cs
src/TensorFlowNET.Core/Operations/math_ops.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Unit testing the operation too.

Adding `Cumsum` operation

---

src/TensorFlowNET.Core/Tensors/Tensor.Operators.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Also unit testing the new operators.

Unit testing `operator *`s. Add missing `operator /`s

---

src/TensorFlowNET.Core/Tensors/Tensor.Operators.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Also unit testing the new operators.

Add missing `operator >`s and `operator <`s

---

src/TensorFlowNET.Core/Tensors/Tensor.Operators.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Also unit testing the new operators.

Add missing `operator >=`s and `operator <=`s

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/Operations/gen_math_ops.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Relative unit test in `OperationTest`.

Adding `logical_and` operator

---

src/TensorFlowHub/Utils.cs

Perhaps you can add more code to implement the hash check ingress of the file and intermittently pass on.

Added features to avoid repeated downloads of running data.

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/Operations/gen_math_ops.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Relative unit test in `OperationTest`.

Adding `logical_not` operator

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/Operations/gen_math_ops.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Relative unit test in `OperationTest`.

Adding `logical_or` operator

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/Operations/gen_math_ops.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Relative unit test in `OperationTest`.

Adding `logical_xor` operator

---

src/TensorFlowNET.Core/APIs/tf.nn.cs

Baby's first PR :)
Let me know what else I need to do.  Not sure if I was supposed to PR master or some other branch.

Add tf.nn.in_top_k

---

CODEOWNERS

You can get more granular in the future but this is a good place to start to see if you like using this feature of github.

Create CODEOWNERS file that defaults to everything

---

src/TensorFlowNET.Core/Keras/BackendBase.cs
src/TensorFlowNET.Core/Operations/OpDefLibrary.cs
src/TensorFlowNET.Core/Python.cs
test/TensorFlowNET.UnitTest/PythonBaseTests.cs

Added python internal function **isinstance()** with all overloads

added isinstance function

---

src/TensorFlowNET.Core/Tensors/Tensor.Operators.cs

Filled in all missing possibilities. Any changes were reflected based on what was already there.

Tensor.Operators: Rewrite using regen-template

---

src/TensorFlowNET.Core/APIs/tf.layers.cs
src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/APIs/tf.tensor.cs
src/TensorFlowNET.Core/Operations/Activation/gen_nn_ops.activations.cs

Added all Keras activations

---

src/TensorFlowHub/TensorFlowHub.csproj
src/TensorFlowNET.Core/TensorFlowNET.Core.csproj
src/TensorFlowNET.Core/Tensors/Tensor.cs
src/TensorFlowNET.Core/Tensors/dtypes.cs

@kerryjiang, Is it ok to upgrade NumSharp to 0.20.2, no breaking changes in your project (TFHub) and compiles successfully.

Upgraded NumSharp to 0.20.2

---

src/TensorFlowNET.Core/Operations/Initializers/VarianceScaling.cs

_compute_fans is buggy in VarianceScaling

---

TensorFlow.NET.sln
src/TensorFlowNET.Core/TensorFlowNET.Core.csproj
src/TensorFlowNET.Hub/TensorFlowNET.Hub.csproj

This makes building the solution much easier

Move NumSharp.Core to nuget reference

---

src/TensorFlowNET.Core/APIs/tf.image.cs
src/TensorFlowNET.Core/Operations/image_ops_impl.cs
test/TensorFlowNET.UnitTest/img_test/TestCrop.cs

Added the crop_and_resize method from https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize.

Add image functions

---

src/TensorFlowNET.Core/APIs/tf.variable.cs
src/TensorFlowNET.Core/Framework/meta_graph.cs
src/TensorFlowNET.Core/Graphs/Graph.cs
src/TensorFlowNET.Core/Summaries/Summary.cs
src/TensorFlowNET.Core/Variables/variable_scope.py.cs
src/TensorFlowNET.Core/Variables/variables.py.cs
src/TensorFlowNET.Core/ops.cs
test/TensorFlowNET.UnitTest/Keras/EmbeddingTest.cs
test/TensorFlowNET.UnitTest/VariableTest.cs

As i wrote in chat, all the casts to List<Type> are very fragile and have side effects with different variable types.
Fixes embedding/ crop test.
Also some refactoring/ removed out-commented code/ useless if/else statements.

Fix collections typing

---

src/TensorFlowNET.Core/APIs/tf.scan.cs
src/TensorFlowNET.Core/Interfaces/IFromMergeVars.cs
src/TensorFlowNET.Core/Operations/ControlFlows/WhileContext.cs
src/TensorFlowNET.Core/Operations/NnOps/BodyItemInRnnWhileLoop.cs
src/TensorFlowNET.Core/Operations/control_flow_ops.cs
src/TensorFlowNET.Core/Operations/functional_ops.cs
src/TensorFlowNET.Core/Operations/map_fn.cs
src/TensorFlowNET.Core/Tensors/TensorShape.cs
test/TensorFlowNET.UnitTest/control_flow_ops_test/WhileContextTestCase.cs
test/TensorFlowNET.UnitTest/functional_ops_test/ScanTestCase.cs

Translated a lot of the code over from the original python and added some of the examples from the documentation as test cases.  Always outputting 0 though so something is missing

Buggy tf.scan + map_fn + tests

---

test/TensorFlowNET.UnitTest/GraphTest.cs

Fix GraphTest, comparing GraphDef directly without converting to JSON

---

test/TensorFlowNET.UnitTest/PythonTest.cs
test/TensorFlowNET.UnitTest/gradients_test/GradientsTest.cs

Fix Float64 equal compare in GradientTest

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/APIs/tf.train.cs
src/TensorFlowNET.Core/Sessions/_FetchHandler.cs
src/TensorFlowNET.Core/Tensors/TF_DataType.cs
src/TensorFlowNET.Core/Tensors/dtypes.cs
src/TensorFlowNET.Core/Training/AdamOptimizer.cs
src/TensorFlowNET.Core/Training/Optimizer.cs

1. add a subtract function
2. fix adamOptimizer no init dtype.
3. fix miss type value.
4. fix type conver performance bug

fix adamOptimizer no init dtype.

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/APIs/tf.nn.cs
src/TensorFlowNET.Core/APIs/tf.random.cs
src/TensorFlowNET.Core/APIs/tf.train.cs

Comments:
1 - I don't speak english.
2 - I am not experienced.
3 - Git is something new for me.
4 - I don't mind redoing if I did it wrong, just tell me.

Exposing some methods already implemented.

---

src/TensorFlowNET.Core/Eager/SafeContextHandle.cs
src/TensorFlowNET.Core/Eager/SafeContextOptionsHandle.cs
src/TensorFlowNET.Core/Graphs/SafeImportGraphDefOptionsHandle.cs
src/TensorFlowNET.Core/Sessions/SafeSessionOptionsHandle.cs
src/TensorFlowNET.Core/Status/SafeStatusHandle.cs

Updates the code for consistency following https://github.com/SciSharp/TensorFlow.NET/pull/565#discussion_r446932522.

Mark SafeHandle interop constructors private

---

src/TensorFlowNET.Core/Attributes/c_api.ops.cs
src/TensorFlowNET.Core/Buffers/Buffer.cs
src/TensorFlowNET.Core/Buffers/SafeBufferHandle.cs
src/TensorFlowNET.Core/Buffers/c_api.buffer.cs
src/TensorFlowNET.Core/Framework/importer.cs
src/TensorFlowNET.Core/Framework/op_def_registry.py.cs
src/TensorFlowNET.Core/GraphTransformation/GraphTransformer.cs
src/TensorFlowNET.Core/Graphs/Graph.Export.cs
src/TensorFlowNET.Core/Graphs/Graph.Import.cs
src/TensorFlowNET.Core/Graphs/c_api.graph.cs
src/TensorFlowNET.Core/Operations/Operation.cs
src/TensorFlowNET.Core/Operations/c_api.ops.cs
src/TensorFlowNET.Core/Util/SafeHandleLease.cs
test/TensorFlowNET.UnitTest/GraphTest.cs
test/TensorFlowNET.UnitTest/NativeAPI/CApiGradientsTest.cs
test/TensorFlowNET.UnitTest/NativeAPI/c_test_util.cs
test/TensorFlowNET.UnitTest/OperationsTest.cs

Marked as a draft to give me another day to discuss the best way to document `Dangerous*` members in the new API

Implement SafeBufferHandle as a wrapper for TF_Buffer

---

src/TensorFlowNET.Core/Util/SafeHandleExtensions.cs

Implements changes suggested in https://github.com/dotnet/roslyn/pull/43462.

Optimize SafeHandleExtensions.Lease()

---

test/TensorFlowNET.UnitTest/TF_API/GradientTest.cs

some error about gradient variable

---

src/TensorFlowNET.Core/APIs/tf.math.cs
src/TensorFlowNET.Core/Operations/math_ops.cs
src/TensorFlowNET.Core/Tensors/dtypes.cs

* implement math_ops.real, reduce_variance, reduce_std
* add dtype.real_dtype()
* add outward-facing api functions
I tested the build locally and it succeeded with no issues.

implement math_ops.real, reduce_variance, reduce_std

---

src/TensorFlowNET.Core/APIs/tf.debugging.cs
src/TensorFlowNET.Core/Operations/check_ops.cs

* implement check_ops.assert_greater_equal()
* add outward-facing api function
Build succeeded when I built it locally.

implement check_ops.assert_greater_equal()

---

test/TensorFlowNET.UnitTest/Basics/TensorTest.cs

This test case refers to #607 
Currently, this test fails when it tries to perform a bilinear resize, because tensors created with the new keyword don't have an internal operator defined.

Added use case for creating and resizing a tensor.

---

test/TensorFlowNET.UnitTest/Basics/TensorTest.cs

The test case is currently not passed yet.

Add test case for Tensor.assign #653

---

test/TensorFlowNET.UnitTest/ManagedAPI/ControlFlowApiTest.cs

tf.Scan Unit Test

---

README.md

Easier for beginners to the get going if the example actually works

Fixed Keras c# example so it works

---

test/TensorFlowNET.Keras.UnitTest/Layers/LayersTest.cs

This test is written based on Dueliing DQN' s network structure.

Add Custom Keras Layer Test

---

src/TensorFlowNET.Core/Keras/ArgsDefinition/RNNArgs.cs
src/TensorFlowNET.Core/Keras/ArgsDefinition/SimpleRNNArgs.cs
src/TensorFlowNET.Core/Keras/ArgsDefinition/StackedRNNCellsArgs.cs
src/TensorFlowNET.Core/Operations/NnOps/RNNCell.cs
src/TensorFlowNET.Keras/Layers/LayersApi.cs
src/TensorFlowNET.Keras/Layers/RNN.cs
src/TensorFlowNET.Keras/Layers/SimpleRNN.cs
src/TensorFlowNET.Keras/Layers/StackedRNNCells.cs
test/TensorFlowNET.Keras.UnitTest/Layers/LayersTest.cs

I started implementing RNN, SimpleRNN and related code, but I'm not sure yet that I am writing correctly and not creating a mess. please tell me if there is something here that you definitely don't need to do.

Blank SimpleRNN and test for it

---

src/TensorFlowNET.Core/Operations/gen_math_ops.cs

This pull request fixes issue #747.

Fix sign function in eager mode

---

src/TensorFlowNET.Keras/Datasets/MNIST.cs

Rename local variable to match intent of the dataset label

LoadX readability change: rename local variable

---

src/TensorFlowNET.Core/Keras/ArgsDefinition/Pooling/Pooling1DArgs.cs
src/TensorFlowNET.Keras/Layers/LayersApi.cs
src/TensorFlowNET.Keras/Layers/Pooling/GlobalAveragePooling1D.cs
src/TensorFlowNET.Keras/Layers/Pooling/GlobalMaxPooling1D.cs
src/TensorFlowNET.Keras/Layers/Pooling/GlobalMaxPooling2D.cs
src/TensorFlowNET.Keras/Layers/Pooling/GlobalPooling1D.cs
src/TensorFlowNET.Keras/Layers/Pooling/MaxPooling1D.cs
src/TensorFlowNET.Keras/Layers/Pooling/Pooling1D.cs
test/TensorFlowNET.Keras.UnitTest/Layers/PoolingTest.cs

Added support for some 1D pooling Keras APIs. These can sometimes be useful for processing text with convolutions. Still need to add 1D convolution APIs.

Pooling 1d

---

test/TensorFlowNET.UnitTest/GradientTest/GradientEagerTest.cs

See issue #787 
Added tests with ignore attribute that demonstrates the issue. NB the outputs from the gradient are simply the input argument

SquaredDifference gives incorrect gradients

---

src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/ELUArgs.cs
src/TensorFlowNET.Core/Keras/ArgsDefinition/Activation/SoftmaxArgs.cs
src/TensorFlowNET.Core/Keras/ArgsDefinition/Cropping/Cropping2DArgs.cs
src/TensorFlowNET.Core/Keras/ArgsDefinition/Cropping/Cropping3DArgs.cs
src/TensorFlowNET.Core/Keras/ArgsDefinition/Cropping/CroppingArgs.cs
src/TensorFlowNET.Core/Keras/ArgsDefinition/Reshaping/PermuteArgs.cs
src/TensorFlowNET.Keras/Layers/Activation/ELU.cs
src/TensorFlowNET.Keras/Layers/Activation/Exponential.cs
src/TensorFlowNET.Keras/Layers/Activation/HardSigmoid.cs
src/TensorFlowNET.Keras/Layers/Activation/SELU.cs
src/TensorFlowNET.Keras/Layers/Activation/Softmax.cs
src/TensorFlowNET.Keras/Layers/Activation/Softplus.cs
src/TensorFlowNET.Keras/Layers/Activation/Softsign.cs
src/TensorFlowNET.Keras/Layers/Activation/Swish.cs
src/TensorFlowNET.Keras/Layers/Activation/Tanh.cs
src/TensorFlowNET.Keras/Layers/Cropping/Cropping1D.cs
src/TensorFlowNET.Keras/Layers/Cropping/Cropping2D.cs
src/TensorFlowNET.Keras/Layers/Cropping/Cropping3D.cs
src/TensorFlowNET.Keras/Layers/LayersApi.Activation.cs
src/TensorFlowNET.Keras/Layers/LayersApi.Cropping.cs
src/TensorFlowNET.Keras/Layers/LayersApi.Reshaping.cs
src/TensorFlowNET.Keras/Layers/Reshaping/Permute.cs
test/TensorFlowNET.Keras.UnitTest/Layers/ActivationTest.cs
test/TensorFlowNET.Keras.UnitTest/Layers/Layers.Cropping.Test.cs
test/TensorFlowNET.Keras.UnitTest/Layers/Layers.Reshaping.Test.cs

Layers added:
Cropping1D, Cropping2D, Cropping3D, Permute
ELU, SELU, Softmax, Softsign, Softplus, Exponential, Swish, Tanh, Hard Sigmoid

Added Cropping, Permute, and multiple activation layers to Tensorflow.Keras

---

src/TensorFlowNET.Core/IO/MemmappedFileSystem.cs

Hey, i looked for contribution guidelines (codestyle etc.) but didn't really find any. If there's something wrong with how i named the methods & variables please let me know. Original Tensorflow code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/memmapped_file_system.cc
The implementation here only allows access to existing filesystems

Work on memmapped fs

---

src/TensorFlowNET.Core/Keras/ArgsDefinition/Core/DenseArgs.cs
src/TensorFlowNET.Core/Keras/Regularizers/RegularizerArgs.cs
src/TensorFlowNET.Keras/Engine/Layer.cs
src/TensorFlowNET.Keras/Regularizers/L1.cs
src/TensorFlowNET.Keras/Regularizers/L1L2.cs
src/TensorFlowNET.Keras/Regularizers/L2.cs

don't merge until the finish, but I send PR to review with me.

Initial regularizers.

---

src/TensorFlowNET.Keras/Engine/Model.Fit.cs

Fix IO Exception from keras.fit when the output is redirected.

Fix IO Exception from keras.fit.

---

src/TensorFlowNET.Core/Sessions/BaseSession.cs

Using a local reference ensure that the Status object cannot be disposed before the Dispose. This way it's also possible to use an external Status instance instead of the static one, if needed. (https://github.com/SciSharp/TensorFlow.NET/issues/912)

Use a local Status variable

---

src/TensorFlowNET.Core/NumPy/NDArray.Operators.cs
test/TensorFlowNET.UnitTest/NumPy/OperatorsTest.cs

Should solve https://github.com/SciSharp/TensorFlow.NET/issues/935.
Unit test provided fails on current implementation.

Reimplemented NDArray == and != operators, handling null values

---

src/TensorFlowNET.Core/Operations/gen_array_ops.cs
test/TensorFlowNET.Keras.UnitTest/Gradient.cs

Fix: #760 
Thanks for the test code provided here https://github.com/SciSharp/TensorFlow.NET/issues/760#issuecomment-1453403841

Fix issue #760

---

README.md
docs/README-CN.md

Fix some typo of the latest readme.

Fix some typo of readme.

---

.github/ISSUE_TEMPLATE/blank_issue.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documention_issue.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/performance_issue.yml
.github/ISSUE_TEMPLATE/question.yml

Add some github issue templates. A blank issue template is included for the condition that no template matches the issue.

Add github issue templates.

---

.github/ISSUE_TEMPLATE/blank_issue.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Fix the error of issue templates added by #1002

Fix the error of issue templates.

---

src/TensorFlowNET.Core/Keras/ArgsDefinition/AutoSerializeLayerArgs.cs
src/TensorFlowNET.Core/Keras/Common/CustomizedShapeJsonConverter.cs
src/TensorFlowNET.Core/Tensorflow.Binding.csproj
src/TensorFlowNET.Core/Training/Saving/SavedModel/loader.cs
src/TensorFlowNET.Keras/Utils/generic_utils.cs
test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelLoad.cs

Fix the error when loading VGG19.

---

src/TensorFlowNET.Keras/Engine/Model.Predict.cs

Fix issue if data_handler.steps() > 1
batch_outputs was reduced to one Tensor instead of combine each

Update PredictInternational on Model.Predict.cs

---

src/TensorFlowNET.Core/Keras/IOptimizerApi.cs
src/TensorFlowNET.Keras/Optimizers/AdamW.cs
src/TensorFlowNET.Keras/Optimizers/OptimizerApi.cs

`AdamWeightDecay` optimizer is widely used for training LLM models, I added the `AdamW` optimizer for developers to use easily.

Add a new optimizer

---

src/TensorFlowNET.Core/Gradients/nn_grad.cs
src/TensorFlowNET.Core/Keras/Layers/ILayer.cs
src/TensorFlowNET.Core/Operations/NnOps/RNNCell.cs
src/TensorFlowNET.Keras/Engine/Layer.Apply.cs
src/TensorFlowNET.Keras/Engine/Model.Fit.cs
src/TensorFlowNET.Keras/Layers/Rnn/RNN.cs
src/TensorFlowNET.Keras/Preprocessings/Preprocessing.image_dataset_from_directory.cs
src/TensorFlowNET.Keras/Preprocessings/Preprocessing.paths_and_labels_to_dataset.cs

1. add loss avg_poo_grad funcion
2. add a create folder to dataset funcion
3. fix a ILayer.cs Apply function params

fix same bug

---

src/TensorFlowNET.Core/Keras/IOptimizerApi.cs
src/TensorFlowNET.Core/Training/gen_training_ops.cs
src/TensorFlowNET.Keras/Optimizers/OptimizerApi.cs
src/TensorFlowNET.Keras/Optimizers/SGD.cs

fix: add the momentum parameter's implemention of SGD

---

test/TensorFlowNET.Graph.UnitTest/GradientTest/GradientTest.cs

testAggregationMethodAccumulateN
testAggregationMethodAddN
testAggregationMethodTree
testSingletonIndexedSlices - **broken**
testDependentYs
testPartialDerivatives
testStopGradients - **broken**

Gradient tests which were dependant only on cached_session

---

src/TensorFlowNET.Keras/Engine/Layer.Serialize.cs

Suggested fix to the issue #1181 : [BUG Report + fix]: Saving after loading tf.keras model

fix: Saving a loaded model

---

src/TensorFlowNET.Core/Tensors/tensor_util.cs

Now all casts between int<->float<->double tensors work correctly with any ranks however with little loss of performance

fix: More generic array cast
